apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.ports.web.externalPort }}
      targetPort: {{ .Values.service.ports.web.internalPort }}
      protocol: TCP
      name: web
    - port: {{ .Values.service.ports.grpc.externalPort }}
      targetPort: {{ .Values.service.ports.grpc.internalPort }}
      protocol: TCP
      name: grpc
  selector:
    app: {{ .Values.service.name }}
    release: {{ .Release.Name }}
